# Configurations
title:            Jerry's CodeBook! #Jekyll Gitbook
longtitle:        Jerry's CodeBook! #Jekyll Gitbook
author:           jerrykim91 #HE Tao
email:            jerrykim91.pub@gmail.com #sighingnow@gmail.com
description: >
  This is jerry CodeBook!
# Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3
github_username:  jerrykim91

# url:              'https://sighingnow.github.io'
# baseurl:          '/jekyll-gitbook'

# 사이트 업로드시
url:              'https://jerrykim91.github.io' # the base hostname & protocol for your site, e.g. http://example.com
baseurl:          'https://jerrykim91.github.io' #'/Jerry's_Codebook' # the subpath of your site, e.g. /blog -> 타이틀 링트 그리고 베이스 링크

# 로컬 작업시
# url:              'http://127.0.0.1:4000/' # the base hostname & protocol for your site, e.g. http://example.com
# baseurl:          '' # 로컬 작업시 

rss:              RSS


tracker:
  google_analytics: "G-M2VSGWT6VH" #"<YOUR GOOGLE ANALYTICS KEY, e.g, UA-xxxxxx-x>"


toc:
  enabled: true
  h_min: 1
  h_max: 2 #3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: github
# syntax_highlighter_style 옵션(rouge참조) : {colorful:흐리멍텅함- 내취향아님},{github:}

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
# permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts


destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jemoji


utterances:
  enable: true
  repo: Jerrykim91/blog-comment
  issue_term: title
  theme: github-light


# 상위 디렉토리 추가 
collections:
  Intro:
    output: true
    permalink: /:path/
    order:

  # Pages:
  #   output: true
  #   permalink: /:collection/:path/
  #   order:

  MachineVision:
    output: true
    permalink: /:collection/:path/
    order:

  Python:
    output: true
    permalink: /:collection/:path/
    order:

  MachineLearning:
    output: true
    permalink: /:collection/:path/
    order:
      - 2022-04-06-Feature-Scalining.md

  Analysis:
    output: true
    permalink: /:collection/:path/
    order:
      # 아래부터 상위에 노출됨 
      - 2022-03-31-Pandas_2.md
      - 2021-10-15-1.1.Pandas_1.md

  Web:
    output: true
    permalink: /:collection/:path/
    # order:
