# Configurations
title:            Do it
longtitle:        Just Do it. That's me.
author:           hyowon
email:            sun4131@gmail.com
description: >
  몰라

version:          1.0

url:              'https://jerrykim91.github.io'
# url:              'http://localhost:4000'
baseurl:          ''
# rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

# pandoc:
#   format: html5
#   highlight-style: tango
#   extensions:
#     - smart
#     - mathjax

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        none

excerpt_separator: "<!--more-->"

# Navigation
navigation:
- text: Blog
  url: /blog/
- text: Archive
  url: /archive/
- text: Github
  url: https://github.com/jerrykim91
  external: true
# - text: Portfolio
#   url: 
#   external: true

exclude:
  - _drafts

#Social Media links
# social:
#   github:         sighingnow
#   facebook:       sighingnow

# Google Analytics
# gahandler:        'UA-124803592-1'

# CNZZ
# cnzzhandler:      '1277366039'

# Disqus
# disqushandler:    'sighingnow'

# Blog Configurations
paginate:         10 # Posts per page on the blog index
paginate_path:    '/blog/page:num'
destination:      ./_site
incremental:      true
regenerate:       false

languages: ["en", "ko"] # 지원하고자 하는 언어
default_lang: "ko" # 컨텐츠의 기본 언어
exclude_from_localization: ["image"] # 루트 레벨 폴더 중 다국어 기능 제외 시킬 폴더
parallel_localizaion: false # 윈도우에서는 버그가 있어서 false로 해야 동작한다고 합니다.

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-polyglot

# future : true  # 미래의 포스트 보여주는 옵션